name: sunnytravel_app
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  flutter_swiper: ^1.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - images/dali.jpg
   - images/qinghai.jpg
   - images/tianjin.jpg
   - images/splash.jpg
   - images/als2.jpg
   - images/am2.jpg
   - images/bj.jpg
   - images/bj2.jpg
   - images/cd2.jpg
   - images/cq.jpg
   - images/dh2.jpg
   - images/dl.jpg
   - images/dl2.jpg
   - images/gl.jpg
   - images/hgs2.jpg
   - images/hk.jpg
   - images/hlbe2.jpg
   - images/hz.jpg
   - images/km2.jpg
   - images/lj.jpg
   - images/ls.jpg
   - images/mh.jpg
   - images/qd.jpg
   - images/qh.jpg
   - images/sh.jpg
   - images/snj2.jpg
   - images/sy.jpg
   - images/sz.jpg
   - images/tb.jpg
   - images/tj.jpg
   - images/wts2.jpg
   - images/wy.jpg
   - images/wys2.jpg
   - images/xian.jpg
   - images/xm.jpg
   - images/yz2.jpg
   - images/zjj.jpg
   - images/spring.jpg
   - images/summer.jpg
   - images/autumn.jpg
   - images/winter.jpg
   - images/hkmt.jpg
   - images/central.jpg
   - images/east.jpg
   - images/south.jpg
   - images/north.jpg
   - images/northeast.jpg
   - images/southwest.jpg
   - images/northwest.jpg
   - images/2.0x/dali.jpg
   - images/2.0x/qinghai.jpg
   - images/2.0x/tianjin.jpg
   - images/2.0x/splash.jpg
   - images/2.0x/als2.jpg
   - images/2.0x/am2.jpg
   - images/2.0x/bj.jpg
   - images/2.0x/bj2.jpg
   - images/2.0x/cd2.jpg
   - images/2.0x/cq.jpg
   - images/2.0x/dh2.jpg
   - images/2.0x/dl.jpg
   - images/2.0x/dl2.jpg
   - images/2.0x/gl.jpg
   - images/2.0x/hgs2.jpg
   - images/2.0x/hk.jpg
   - images/2.0x/hlbe2.jpg
   - images/2.0x/hz.jpg
   - images/2.0x/km2.jpg
   - images/2.0x/lj.jpg
   - images/2.0x/ls.jpg
   - images/2.0x/mh.jpg
   - images/2.0x/qd.jpg
   - images/2.0x/qh.jpg
   - images/2.0x/sh.jpg
   - images/2.0x/snj2.jpg
   - images/2.0x/sy.jpg
   - images/2.0x/sz.jpg
   - images/2.0x/tb.jpg
   - images/2.0x/tj.jpg
   - images/2.0x/wts2.jpg
   - images/2.0x/wy.jpg
   - images/2.0x/wys2.jpg
   - images/2.0x/xian.jpg
   - images/2.0x/xm.jpg
   - images/2.0x/yz2.jpg
   - images/2.0x/zjj.jpg
   - images/2.0x/spring.jpg
   - images/2.0x/summer.jpg
   - images/2.0x/autumn.jpg
   - images/2.0x/winter.jpg
   - images/2.0x/hkmt.jpg
   - images/2.0x/central.jpg
   - images/2.0x/east.jpg
   - images/2.0x/south.jpg
   - images/2.0x/north.jpg
   - images/2.0x/northeast.jpg
   - images/2.0x/southwest.jpg
   - images/2.0x/northwest.jpg
   - images/3.0x/dali.jpg
   - images/3.0x/qinghai.jpg
   - images/3.0x/tianjin.jpg
   - images/3.0x/splash.jpg
   - images/3.0x/als2.jpg
   - images/3.0x/am2.jpg
   - images/3.0x/bj.jpg
   - images/3.0x/bj2.jpg
   - images/3.0x/cd2.jpg
   - images/3.0x/cq.jpg
   - images/3.0x/dh2.jpg
   - images/3.0x/dl.jpg
   - images/3.0x/dl2.jpg
   - images/3.0x/gl.jpg
   - images/3.0x/hgs2.jpg
   - images/3.0x/hk.jpg
   - images/3.0x/hlbe2.jpg
   - images/3.0x/hz.jpg
   - images/3.0x/km2.jpg
   - images/3.0x/lj.jpg
   - images/3.0x/ls.jpg
   - images/3.0x/mh.jpg
   - images/3.0x/qd.jpg
   - images/3.0x/qh.jpg
   - images/3.0x/sh.jpg
   - images/3.0x/snj2.jpg
   - images/3.0x/sy.jpg
   - images/3.0x/sz.jpg
   - images/3.0x/tb.jpg
   - images/3.0x/tj.jpg
   - images/3.0x/wts2.jpg
   - images/3.0x/wy.jpg
   - images/3.0x/wys2.jpg
   - images/3.0x/xian.jpg
   - images/3.0x/xm.jpg
   - images/3.0x/yz2.jpg
   - images/3.0x/zjj.jpg
   - images/3.0x/spring.jpg
   - images/3.0x/summer.jpg
   - images/3.0x/autumn.jpg
   - images/3.0x/winter.jpg
   - images/3.0x/hkmt.jpg
   - images/3.0x/central.jpg
   - images/3.0x/east.jpg
   - images/3.0x/south.jpg
   - images/3.0x/north.jpg
   - images/3.0x/northeast.jpg
   - images/3.0x/southwest.jpg
   - images/3.0x/northwest.jpg
   - images/4.0x/dali.jpg
   - images/4.0x/qinghai.jpg
   - images/4.0x/tianjin.jpg
   - images/4.0x/splash.jpg
   - images/4.0x/als2.jpg
   - images/4.0x/am2.jpg
   - images/4.0x/bj.jpg
   - images/4.0x/bj2.jpg
   - images/4.0x/cd2.jpg
   - images/4.0x/cq.jpg
   - images/4.0x/dh2.jpg
   - images/4.0x/dl.jpg
   - images/4.0x/dl2.jpg
   - images/4.0x/gl.jpg
   - images/4.0x/hgs2.jpg
   - images/4.0x/hk.jpg
   - images/4.0x/hlbe2.jpg
   - images/4.0x/hz.jpg
   - images/4.0x/km2.jpg
   - images/4.0x/lj.jpg
   - images/4.0x/ls.jpg
   - images/4.0x/mh.jpg
   - images/4.0x/qd.jpg
   - images/4.0x/qh.jpg
   - images/4.0x/sh.jpg
   - images/4.0x/snj2.jpg
   - images/4.0x/sy.jpg
   - images/4.0x/sz.jpg
   - images/4.0x/tb.jpg
   - images/4.0x/tj.jpg
   - images/4.0x/wts2.jpg
   - images/4.0x/wy.jpg
   - images/4.0x/wys2.jpg
   - images/4.0x/xian.jpg
   - images/4.0x/xm.jpg
   - images/4.0x/yz2.jpg
   - images/4.0x/zjj.jpg
   - images/4.0x/spring.jpg
   - images/4.0x/summer.jpg
   - images/4.0x/autumn.jpg
   - images/4.0x/winter.jpg
   - images/4.0x/hkmt.jpg
   - images/4.0x/central.jpg
   - images/4.0x/east.jpg
   - images/4.0x/south.jpg
   - images/4.0x/north.jpg
   - images/4.0x/northeast.jpg
   - images/4.0x/southwest.jpg
   - images/4.0x/northwest.jpg


 # An image asset can refer to one or more resolution-specific "variants", see
 # https://flutter.dev/assets-and-images/#resolution-aware.

 # For details regarding adding assets from package dependencies, see
 # https://flutter.dev/assets-and-images/#from-packages

 # To add custom fonts to your application, add a fonts section here,
 # in this "flutter" section. Each entry in this list should have a
 # "family" key with the font family name, and a "fonts" key with a
 # list giving the asset and other descriptors for the font. For
 # example:
 # fonts:
 #   - family: Schyler
 #     fonts:
 #       - asset: fonts/Schyler-Regular.ttf
 #       - asset: fonts/Schyler-Italic.ttf
 #         style: italic
 #   - family: Trajan Pro
 #     fonts:
 #       - asset: fonts/TrajanPro.ttf
 #       - asset: fonts/TrajanPro_Bold.ttf
 #         weight: 700
 #
 # For details regarding fonts from package dependencies,
 # see https://flutter.dev/custom-fonts/#from-packages
